services:
  schedule-bot:
    build: .
    stop_signal: SIGINT
    volumes:
    - db:/home/app/db
    environment:
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
      VK_BOT_TOKEN: ${VK_BOT_TOKEN}
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
      DB_PATH: /home/app/db

volumes:
  db: