services:
  schedule-bot:
    build: .
    stop_signal: SIGINT
    environment:
      VK_BOT_TOKEN: ${VK_BOT_TOKEN}
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
      OPENAI_MODEL: ${OPENAI_MODEL}
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
      MONGO_HOST: mongo
      MONGO_USER: root
      MONGO_PASSWORD: root
      MONGO_PORT: 27017
      REDIS_HOST: keydb
      REDIS_PORT: 6379
      OPENAI_KEYS_FILE: /home/app/openai-keys.txt
    volumes:
      - ./openai-keys.txt:/home/app/openai-keys.txt:ro

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      #ports:
      #  - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
  keydb:
      image: eqalpha/keydb:alpine
      command: keydb-server 
        --server-threads ${KEYDB_THREADS} 
        --appendonly no 
        --maxmemory ${KEYDB_MAX_MEMORY}
        --maxmemory-policy allkeys-lru
